name: google_route_optimization_api
description: A Dart package to interact with Google Route Optimization API using OAuth2.
version: 1.0.0
repository: https://github.com/mohamadalghanem474/google_route_optimization_api
topics:
  - firebase
  - api
  - google
  - ptimization
  - route

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.4
  googleapis_auth: ^1.6.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  json_serializable: ^6.7.1
  lints: ^5.0.0
  test: ^1.24.0